export interface InputInterface {
    name: string,
    control: Function,
    keyboardType?: string,
    defaultValue?: string,
    autoCapitalize?: string,
    errorStyle?: object,
    errorMessage?: string,
    placeholder?: string,
    editable?: boolean
    headerStyles?: object,
    maxLength?: number,
    multiline?: number,
    numberOfLines?: number,
    headerTitle?: string,
    getValues?: Function,
    setValue?: Function,
    leftIcon?: any,
    secureTextEntry?: boolean,
    rightIconShow?: string,
    rightIconHide?: string,
    inputStyle?: object,
  }
